name: Release build
on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Scm
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action Release"
          mvn -B release:prepare -D"pushChanges=false" -D"scmCommentPrefix=[ci skip] " -D"tagNameFormat=v@{project.version}" -D"preparationGoals=clean package"
          git clean -f -d
          git fetch origin develop
          git checkout develop
          git merge release
          git push --follow-tags origin release
          git push origin develop
